#!/bin/sh

i=0
while [ ! -f /tmp/.X0-lock ];
do
	let i++
	echo -ne "Waiting X $i\r"
	sleep 0.1
done

j=0
while [ ! -f /tmp/.wm_ready ];
do
	let j++
	echo -ne "Waiting wm_ready $j\r"
	sleep 0.1
done

if [ ! -e /tmp/restart ]; then
	if [ -x /usr/bin/boot-animation ]; then
		/usr/bin/boot-animation --start &
		sleep 1
	fi
fi
